In [108]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy
from scipy.optimize import curve_fit

In [90]:
d1 = [28,70,109,150,190]
d2 = [29,69,110,150,190]
d3 = [30,70,110,150,190]
N = [1,2,3,4,5]
d = []
std = []
for x in range(len(d3)):
    #print(x)
     d.append(np.mean([d1[x],d2[x],d3[x]]))
     std.append(np.std([d1[x],d2[x],d3[x]]))
df = pd.DataFrame()
df["markings"] = d
df["cycles"] = N
df["standard deviation distances"] = std

df["actual distance"] = df["markings"]/df["cycles"]

In [91]:
df["micrometers"] = df["actual distance"].apply(lambda a: a*2)

In [92]:
df["D_nano"] = df["micrometers"].apply(lambda b: b*1000)

In [93]:
df

,markings,cycles,standard deviation distances,actual distance,micrometers,D_nano
0,29.000000,1,0.816497,29.000000,58.000000,58000.000000
1,69.666667,2,0.471405,34.833333,69.666667,69666.666667
2,109.666667,3,0.471405,36.555556,73.111111,73111.111111
3,150.000000,4,0.000000,37.500000,75.000000,75000.000000
4,190.000000,5,0.000000,38.000000,76.000000,76000.000000

In [ ]:
def sep(distance):

    av_wav = (576.9599+579.0664)/2

    return (av_wav**2)/(2*distance)

def error(distance):

    av_wav = (576.9599+579.0664)/2

    return (av_wav**2)/(2*distance**2)

def y(m,x,b):
    return m*x+b

In [95]:
separation = sep(np.mean(df["D_nano"]))

In [96]:
separation

2.3743626138315723

In [97]:
std = np.std(df["D_nano"])

In [98]:
err = error(np.mean(df["D_nano"]))*std

In [105]:
err

0.22086699511044786

In [99]:
actual = abs(576.9599-579.0664)

In [100]:
actual

2.1065000000000964

In [101]:
(separation-actual)/actual

0.12716003504935375

In [103]:
df["separation"] = df["D_nano"].apply(sep)

In [104]:
df

,markings,cycles,standard deviation distances,actual distance,micrometers,D_nano,separation
0,29.000000,1,0.816497,29.000000,58.000000,58000.000000,2.880166
1,69.666667,2,0.471405,34.833333,69.666667,69666.666667,2.397841
2,109.666667,3,0.471405,36.555556,73.111111,73111.111111,2.284873
3,150.000000,4,0.000000,37.500000,75.000000,75000.000000,2.227328
4,190.000000,5,0.000000,38.000000,76.000000,76000.000000,2.198021

In [106]:
df.to_csv("Hg.csv")